name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # YOUR DEPENDENCIES
  image_picker: ^1.0.7
  fl_chart: ^1.1.1
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  logger: ^2.4.0
  path_provider: ^2.1.2

  # ðŸ“Œ WAJIB UNTUK UPLOAD FILE
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
